name: Build and Deploy Code

on: [push, pull_request]

jobs:
  myjob1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: welcome
        run: echo "Welcome to the GitHub Actions workflow!"
